import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e0e2e8",
        "on-tertiary-fixed-variant": "#544600",
        tertiary: "#fff9f0",
        "on-primary-container": "#006c71",
        "surface-container": "#1c2024",
        "surface-tint": "#00dce5",
        outline: "#849495",
        "on-surface": "#e0e2e8",
        "on-surface-variant": "#b9caca",
        "primary-fixed-dim": "#00dce5",
        "on-primary-fixed-variant": "#004f53",
        background: "#101418",
        "surface-dim": "#101418",
        "secondary-fixed": "#dee2ec",
        "on-secondary": "#2c3138",
        "on-error": "#690005",
        "on-primary-fixed": "#002021",
        surface: "#101418",
        "tertiary-fixed-dim": "#e7c427",
        "on-secondary-fixed-variant": "#42474f",
        "on-primary": "#003739",
        "surface-container-highest": "#31353a",
        "tertiary-fixed": "#ffe16c",
        "primary-fixed": "#63f7ff",
        "primary-container": "#00f5ff",
        "on-tertiary-container": "#736000",
        "on-background": "#e0e2e8",
        "inverse-primary": "#00696e",
        "on-error-container": "#ffdad6",
        "secondary-container": "#42474f",
        "on-tertiary": "#3a3000",
        "surface-container-lowest": "#0b0f13",
        "surface-bright": "#363a3e",
        "surface-variant": "#31353a",
        "surface-container-low": "#181c20",
        error: "#ffb4ab",
        "on-secondary-fixed": "#171c23",
        "tertiary-container": "#ffdb3f",
        "secondary-fixed-dim": "#c2c7d0",
        secondary: "#c2c7d0",
        primary: "#e9feff",
        "on-tertiary-fixed": "#221b00",
        "outline-variant": "#3a494a",
        "inverse-on-surface": "#2d3135",
        "on-secondary-container": "#b1b5bf",
        "error-container": "#93000a",
        "surface-container-high": "#262a2f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        unit: "4px",
        gutter: "16px",
        md: "16px",
        sm: "8px",
        xl: "40px",
        margin: "24px",
        lg: "24px",
      },
      fontFamily: {
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "code-sm": ["JetBrains Mono"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "headline-xl": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "headline-sm": [
          "18px",
          { lineHeight: "24px", fontWeight: "600" },
        ],
        "label-caps": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "700",
          },
        ],
        "body-sm": [
          "13px",
          { lineHeight: "20px", fontWeight: "400" },
        ],
        "code-md": [
          "13px",
          { lineHeight: "20px", fontWeight: "400" },
        ],
        "code-sm": [
          "12px",
          { lineHeight: "18px", fontWeight: "400" },
        ],
        "body-md": [
          "14px",
          { lineHeight: "22px", fontWeight: "400" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
